[package]
name = "manifold"
version = "0.1.0"
edition = "2021"
authors = ["Kye Cedar <dev@kye.dog>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.31.1"
